name: coverage

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install npm dependencies
      run: yarn install

    - name: Prepare src folder for generating coverage report
      run: yarn nyc:instrument

    - name: Test & publish code coverage to codeclimate.com
      uses: paambaati/codeclimate-action@v2.3.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: yarn cy:run
